apiVersion: cloud-control.gpu.kyma-project.io/v1beta1
kind: GpuCluster
metadata:
  labels:
    app.kubernetes.io/name: gpu-module
    app.kubernetes.io/managed-by: kustomize
  name: gpucluster-sample
spec:
  # TODO(user): Add fields here
